### ISSUE TITLE
エラーが出る

### ISSUE THREAD

**Issue by tkgshn** [tkgshn/DeepYohji#2]
![image](https://user-images.githubusercontent.com/45249410/85857155-44a83900-b7f4-11ea-9133-07b7df1b33a1.png)

[これ](https://qiita.com/berry-clione/items/c37f292231434fd2067a)を参考にしてて、TensorFlowのアップデートにコードを少し変えて対応した。コメント欄と同じようなエラーが出る

>Traceback (most recent call last):
  File "keras_dcgan.py", line 270, in <module>
    c=c
  File "keras_dcgan.py", line 137, in train
    idx = np.random.randint(0, X_train.shape[0], half_batch)
  File "mtrand.pyx", line 747, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1270, in numpy.random._bounded_integers._rand_int64
ValueError: low >= high

**Comment by tkgshn** [comment]
https://qiita.com/berry-clione/items/c37f292231434fd2067a
